version: '3.6'

services:
  mkdocs-material:
    build:
      context: "./"
      no_cache: true
    environment:
      - GITHUB_UI=https://github.com/CX-Box/cxbox-code-samples/tree
      - github_raw_doc=/docs/documentation
      - github_raw=/docs
      - GITHUB_BRANCH=main
      - CODE_SAMPLES=http://code-samples.cxbox.org
      - DEMO=http://demo.cxbox.org
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
    expose:
      -  8000

