site_name: CXBox Documentation

# Структура навигации генерируемого сайта.
nav:
  - Home: index.md
  - What’s new: new/whatsnew.md
  - Versions :
      - cxbox:
        - v2.0.10: new/version2010.md
        - v2.0.9: new/version209.md
        - v2.0.8: new/version208.md
        - v2.0.7: new/version207.md
        - v2.0.6: new/version206.md
        - v2.0.5: new/version205.md
        - v2.0.4: new/version204.md
        - v2.0.3: new/version203.md
        - v2.0.2: new/version202.md
        - v2.0.1: new/version201.md
        - v2.0.0: new/version200.md
        - v1.0.1: new/version101.md
        - v1.0.0: new/version100.md
  - Guides for work with documentation:
    - For analysts: guide/analystguide/analystguide.md
    - For developers: guide/developerguide/developerguide.md
  - Getting started cxbox:
      - For developers:
        - Basic: gettingstarted/getstartedfordevelopers.md
        - Postgres:
          - Basic: gettingstarted/postgres/getstartedfordeveloperspostgres.md
          - Add environment: gettingstarted/postgres/addenvironment.md
          - Add screen: gettingstarted/postgres/addscreen.md
          - Add view: gettingstarted/postgres/addview.md
          - Add widget and field: gettingstarted/postgres/addwidget.md
        - Microservice:
          - Basic: gettingstarted/microservice/getstartedfordevelopersmicroservice.md
          - Add environment: gettingstarted/microservice/addenvironment.md
          - Add screen: gettingstarted/microservice/addscreen.md
          - Add view: gettingstarted/microservice/addview.md
          - Add widget: gettingstarted/microservice/addwidget.md
          - Add field: gettingstarted/microservice/addfield.md
  - Field types:
      - Basic: widget/fields/fieldtypes.md
      - SearchOperation for filtering: widget/fields/filtersearchoperation.md
      - Field input: widget/fields/field/input/input.md
      - Field date: widget/fields/field/date/date.md
      - Field dateTime: widget/fields/field/dateTime/dateTime.md
      - Field dateTimeWithSeconds: widget/fields/field/dateTimeWithSeconds/dateTimeWithSeconds.md
      - Field time: widget/fields/field/time/time.md
      - Field number: widget/fields/field/number/number.md
      - Field percent: widget/fields/field/percent/percent.md
      - Field hidden: widget/fields/field/hidden/hidden.md
      - Field text: widget/fields/field/text/text.md
      - Field radio: widget/fields/field/radio/radio.md
      - Field checkbox: widget/fields/field/checkbox/checkbox.md
      - Field money: widget/fields/field/money/money.md
      - Field dictionary: widget/fields/field/dictionary/dictionary.md
      - Field fileUpload: widget/fields/field/fileUpload/fileUpload.md
      - Field pickList: widget/fields/field/pickList/pickList.md
      - Field inlinePickList: widget/fields/field/inlinePickList/inlinePickList.md
      - Field hint: widget/fields/field/hint/hint.md
      - Field multifield: widget/fields/field/multifield/multifield.md
      - Field multivalue: widget/fields/field/multivalue/multivalue.md
      - Field multipleSelect: widget/fields/field/multipleSelect/multipleSelect.md
      - Field multivalueHover: widget/fields/field/multivalueHover/multivalueHover.md
  - Widget types:
      - Basic: widget/type/widget.md
      - Widget Form: widget/type/form/form.md
      - Widget Info: widget/type/info/info.md
      - Widget List: widget/type/list/list.md
      - Widget AdditionalList: widget/type/additionallist/additionallist.md
      - Widget FormPopup: widget/type/formpopup/formpopup.md
      - Widget AdditionalInfo: widget/type/additionalinfo/additionalinfo.md
      - Widget StatsBlock: widget/type/statblocks/statblocks.md
      - Widget PickListPopup: widget/type/picklistpopup/picklistpopup.md
      - Widget GroupingHierarchy: widget/type/groupinghierarchy/groupinghierarchy.md
      - Property:
         - Show condition: widget/type/property/showcondition/showcondition.md
         - Filtration: widget/type/property/filtration/filtration.md
         - Pagination: widget/type/property/pagination/pagination.md
         - Default page limit: widget/type/property/defaultlimitpage/defaultlimitpage.md
         - Sorting: widget/type/property/sorting/sorting.md
         - Export:
             - Excel: widget/type/property/export/excel/excel.md

  - Navigation:
      - Tabs:
        - Standard:
          - Basic: navigation/tabs/standard/basic/tab.md
          - Basic for developer: navigation/tabs/standard/basicdevelop/tabfordevelop.md
      - View:
          - Basic: navigation/view/view.md
      - Screen:
          - Basic: navigation/screen/screen.md
          - Tabs:  navigation/tabs/tab.md
  - Repository elements:
      - Basic: environment/repository.md
      - Entity: environment/entity/entity.md
      - DTO: environment/dto/dto.md
      - Service: environment/service/service.md
      - MetaBuilder:
          - Basic: environment/meta/metabuilder.md
          - buildIndependentMeta:
            - defaultGroupingHierarchy: environment/meta/buildindependentmeta/defaultgh.md
      - Controller: environment/controller/controller.md
  - Features:
      - Actions: features/element/actions/actions.md
      - Authorization:
        - Basic Authorization: features/element/authorization/basic/basicauthorization.md
        - Keycloak Authorization: features/element/authorization/keycloak/keycloakauthorization.md
      - Database:
        - Oracle: features/element/database/oracle/oraclebd.md
        - Postgres: features/element/database/postgres/postgresbd.md
      - DrillDown:
        - Basic: features/element/drilldown/drilldown.md
        - DrillDown Types: features/element/drilldown/drilldowntype.md
      - FileStorage:
        - Basic: features/element/filestorage/fileStorage.md
        - Minio: features/element/filestorage/minio.md
      - Monitoring tools:
        - Performance Metrics: features/element/monitoringtools/metrics/performancemetrics.md
      - Microservices:
        - Basic: features/element/microservices/microservices.md
        - Get started:
            - Connecting an existing microservices: features/element/microservices/existingmicroservices/existingmicroservices.md
            - Create microservices with data: features/element/microservices/createmicroservices/createmicroservices.md
      - Notifications:
        - Sent to email: features/element/notifications/email/email.md
        - Push: features/element/notifications/push/websocket.md
  - Advanced customization:
      - DrillDown: advancedCustomization/element/drilldown/drilldown.md
      - Validation: advancedCustomization/element/validation/validation.md
      - Filtration: advancedCustomization/element/filtration/filtration.md
      - SearchParameter: advancedCustomization/element/searchparameter/searchparameter.md
  - Plugin: plugin/plugin.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - stylesheets/extra.css

theme:
  font:
    text: Roboto
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/logo.svg
  logo: assets/logo.svg
  name: material
  highlightjs: true
  hljs_languages:
    - json
    - java
  features:
    - navigation.sections
    - search.highlight
    - content.action.edit
  icon:
    edit: material/pencil
    view: material/eye
plugins:
  - search
  - markdownextradata
  - redirects:
      redirect_maps:
        'widget_field_input.md': 'widget/fields/field/input/input.md'
        'widget_field_dictionary.md': 'widget/fields/field/dictionary/dictionary.md'
        'widget_field_hidden.md': 'widget/fields/field/hidden/hidden.md'
        'widget_field_text.md': 'widget/fields/field/text/text.md'
        'widget_field_date.md': 'widget/fields/field/date/date.md'
        'widget_field_dateTime.md': 'widget/fields/field/dateTime/dateTime.md'
        'widget_field_dateTimeWithSeconds.md': 'widget/fields/field/dateTimeWithSeconds/dateTimeWithSeconds.md'
        'widget_field_number.md': 'widget/fields/field/number/number.md'
        'widget_field_money.md': 'widget/fields/field/money/money.md'
        'widget_field_percent.md': 'widget/fields/field/percent/percent.md'
        'widget_field_radio.md': 'widget/fields/field/radio/radio.md'
        'widget_field_checkbox.md': 'widget/fields/field/checkbox/checkbox.md'
        'widget_field_fileUpload.md': 'widget/fields/field/fileUpload/fileUpload.md'
        'widget_field_pickList.md': 'widget/fields/field/pickList/pickList.md'
        'widget_field_inlinePickList.md': 'widget/fields/field/inlinePickList/inlinePickList.md'
        'widget_field_multifield.md': 'widget/fields/field/multifield/multifield.md'
        'widget_field_multivalue.md': 'widget/fields/field/multivalue/multivalue.md'
        'widget_field_multipleSelect.md': 'widget/fields/field/multipleSelect/multipleSelect.md'
        'widget_field_hint.md': 'widget/fields/field/hint/hint.md'
        'widget_field_multivalueHover.md': 'widget/fields/field/multivalueHover/multivalueHover.md'
        'features_drillDown.md': 'features/element/drilldown/drilldown.md'
        'advancedCustomization_drillDown.md': 'advancedCustomization/element/drilldown/drilldown.md'
        'advancedCustomization_filtration.md': 'advancedCustomization/element/filtration/filtration.md'
        'advancedCustomization_validation.md': 'advancedCustomization/element/validation/validation.md'
        'form.md': 'widget/type/form/form.md'
        'info.md': 'widget/type/info/info.md'
        'list.md': 'widget/type/list/list.md'
        'widget_type_form_popup.md': 'widget/type/formpopup/formpopup.md'
        'widget_type_pick_list_popup.md': 'widget/type/picklistpopup/picklistpopup.md'
        'additionalinfo.md': 'widget/type/additionalinfo/additionalinfo.md'

copyright: Copyright &copy; 2023 (Version 1.1)
repo_url: https://github.com/CX-Box/cxbox-doc
edit_uri: edit/main/docs/

#hooks:
#  - logging/log_manager.py

extra:
  external_links:
    github_ui: !ENV [GITHUB_UI, 'https://github.com/CX-Box/cxbox-code-samples/tree']
    github_raw_doc: !ENV [github_raw_doc, 'documentation']
    github_raw: !ENV [github_raw]
    github_branch: !ENV [GITHUB_BRANCH, 'main']
    code_samples: !ENV [CODE_SAMPLES, 'http://code-samples.cxbox.org']
    demo: !ENV [DEMO, 'http://demo.cxbox.org']
  analytics:
    provider: google
    property: G-SEVVVTLFB8
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/CX-Box/cxbox-doc/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.