site_name: Cxbox Documentation

# Структура навигации генерируемого сайта.
nav:
  - Home: index.md
  - Visual components:
      - Field input(i): widget/fields/field/input/input.md
      - Field date(i): widget/fields/field/date/date.md
      - Field dateTime(i): widget/fields/field/dateTime/dateTime.md
      - Field dateTimeWithSeconds(i): widget/fields/field/dateTimeWithSeconds/dateTimeWithSeconds.md
      - Field number: widget/fields/field/number/number.md
      - Field percent: widget/fields/field/percent/percent.md
      - Field text: widget/fields/field/text/text.md
      - Field checkbox: widget/fields/field/checkbox/checkbox.md
      - Field hidden: widget/fields/field/hidden/hidden.md
      - Field money: widget/fields/field/money/money.md
      - Field dictionary: widget/fields/field/dictionary/dictionary.md
      - Field radio: widget/fields/field/radio/radio.md
      - Field fileUpload: widget/fields/field/fileUpload/fileUpload.md
      - Field pickList: widget/fields/field/pickList/pickList.md
      - Field inlinePickList: widget/fields/field/inlinePickList/inlinePickList.md
      - Field multifield: widget/fields/field/multifield/multifield.md
      - Field multivalue: widget/fields/field/multivalue/multivalue.md
      - Field multipleSelect: widget/fields/field/multipleSelect/multipleSelect.md
      - Field hint: widget/fields/field/hint/hint.md
      - Field multivalueHover: widget/fields/field/multivalueHover/multivalueHover.md
  - Features:
      - DrillDown: features/element/drillDown/drillDown.md
      - Filtration: features/element/filtration/filtration.md
  - Advanced customization:
      - DrillDown: advancedCustomization/element/drillDown/drillDown.md
      - Validation: advancedCustomization/element/validation/validation.md
      - Filtration: advancedCustomization/element/filtration/filtration.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - json
    - java
  features:
    - navigation.sections
    - search.highlight
    - content.action.edit
  icon:
    edit: material/pencil
    view: material/eye
plugins:
  - search
  - redirects:
      redirect_maps:
        'widget_field_input.md': 'widget/fields/field/input/input.md'
        'widget_field_dictionary.md': 'widget/fields/field/dictionary/date.md'
        'widget_field_hidden.md': 'widget/fields/field/hidden/hidden.md'
        'widget_field_text.md': 'widget/fields/field/text/percent.md'
        'widget_field_date.md': 'widget/fields/field/date/date.md'
        'widget_field_dateTime.md': 'widget/fields/field/dateTime/dateTime.md'
        'widget_field_dateTimeWithSeconds.md': 'widget/fields/field/dateTimeWithSeconds/dateTimeWithSeconds.md'
        'widget_field_number.md': 'widget/fields/field/number/number.md'
        'widget_field_money.md': 'widget/fields/field/money/money.md'
        'widget_field_percent.md': 'widget/fields/field/percent/percent.md'
        'widget_field_radio.md': 'widget/fields/field/radio/radio.md'
        'widget_field_checkbox.md': 'widget/fields/field/checkbox/checkbox.md'
        'widget_field_fileUpload.md': 'widget/fields/field/fileUpload/fileUpload.md'
        'widget_field_pickList.md': 'widget/fields/field/pickList/pickList.md'
        'widget_field_inlinePickList.md': 'widget/fields/field/inlinePickList/inlinePickList.md'
        'widget_field_multifield.md': 'widget/fields/field/multifield/multifield.md'
        'widget_field_multivalue.md': 'widget/fields/field/multivalue/multivalue.md'
        'widget_field_multipleSelect.md': 'widget/fields/field/multipleSelect/multipleSelect.md'
        'widget_field_hint.md': 'widget/fields/field/hint/hint.md'
        'widget_field_multivalueHover.md': 'widget/fields/field/multivalueHover/multivalueHover.md'
        'features_drillDown.md': 'features/element/drillDown/drillDown.md'
        'advancedCustomization_drillDown.md': 'advancedCustomization/element/drillDown/drillDown.md'
        'advancedCustomization_filtration.md': 'advancedCustomization/element/filtration/filtration.md'
        'advancedCustomization_validation.md': 'advancedCustomization/element/validation/validation.md'

repo_url: https://github.com/CX-Box/cxbox-doc
edit_uri: edit/main/docs/

extra:
  analytics:
    provider: google
    property: G-SEVVVTLFB8
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/CX-Box/cxbox-doc/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.